### ISSUE TITLE
Low values of Comp and Hall

### ISSUE THREAD

**Issue by bf-yang** [Itaymanes/K-QA#3]
Thanks for your great work!

I select two test cases from the dummy_res.json, and run the run_eval.py. However, the Comp and Hall are too low, nearly 0. Is it correct or there are some mistakes? Thanks.

![1709384968480](https://github.com/Itaymanes/K-QA/assets/82997910/a3497747-2c40-44cd-9f43-bad6a5c03767)

**Comment by Itaymanes** [comment]
In general, yes, it makes sense. 
Note the difference between `Comp` and `Comp_norm` ([here](https://github.com/Itaymanes/K-QA/blob/fc2ad3c139ca1c0fbcbbe131e08161b557ada285/evaluation/metrics.py#L49)). They differ in the number of questions that have been 'answered,' where for `Comp`, the numerator is fixed at 201. For `Comp_norm`, it averages the scores over the two answered questions in your example (0.43 is relatively low but reasonable). `Hall` and `Hall_norm` are equal since there were no contradictions in these two questions, which is also reasonable, given that contradictions are less likely.

You can share the details of the experiment, such as questions, answers, model name, and environment (Azure/OpenAI), so I can reproduce your results. However, I prefer to do it privately, so please write to me.

**Comment by bf-yang** [comment]
@Itaymanes Thanks for your answer. It seems that if I only test subset of results, e.g. 10 test cases, I should see Comp_norm and Hall_norm, rather than Comp and Hall, right?

**Comment by Itaymanes** [comment]
What do you mean by 'should see'?
It is true that if you are examining only a portion of the dataset, Comp_norm and Hall_norm are more meaningful, and it makes sense to use them as the leading metrics.
